### ISSUE TITLE
Total Amount of Effort value not updating upon adding removing hours

### ISSUE THREAD

**Issue by rishinikhil** [frappe/erpnext_price_estimation#5]
Steps to replicate
1. Create an estimate with 3-4 modules, the total amount will be updated
2. Add a couple of entries in setup section and remove a couple of entries in other modules
3. The total effort in hours gets updated
4. The total amount which is hours * total effort, does not get updated
![image](https://github.com/frappe/erpnext_price_estimation/assets/2109432/62b49644-8c5e-4bd2-b6ff-f30ea13db765)

**Comment by Poorvi-R-Bhat** [comment]
Total Amount gets calculated based on the "Total Hourly Rate" Entered. Total Amount = Total Hourly Rate * Total Efforts.
