### ISSUE TITLE
Issue in rendering the form

### ISSUE THREAD

**Issue by Islamation** [frappe/erpnext_price_estimation#7]
Hi Guys,
I already installed the app but when I enter to "erpnext price estimation" DOCTYPE it appeared like this

![image](https://github.com/frappe/erpnext_price_estimation/assets/77942121/7d1a5994-b529-473f-9975-740bb9002fa4)

and when I opened the console this error appeared to me
![image](https://github.com/frappe/erpnext_price_estimation/assets/77942121/c1e398aa-28b8-4702-ba6a-182b35fa5127)

is it compatible with v14?
FYI I installed frappe helper if it was helping
Can you help me to know the reason?

frappe version: v14.67.0
ERPNext version: v14.69.1

Thanks for you all

**Comment by Poorvi-R-Bhat** [comment]
Hello,
The app was developed in v15. Please upgrade to v15 and check.

**Comment by Islamation** [comment]
Thanks Poorvi I'll try to do it
